/**
 * Writes the declarations that type an app's action names and props: a
 * global `CycleWireActions` interface mapping each name to its handler, which
 * narrows `ActionName` and gives `PropsOf` (see src/types.d.ts), and the
 * type of the Vite plugin's `virtual:cyclewire/actions` module.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, relative, sep } from 'node:path';
import { handlerOf } from './names.js';

/** TypeScript imports a source file by the extension it compiles to. */
const EMITTED = { '.ts': '.js', '.tsx': '.jsx', '.mts': '.mjs', '.cts': '.cjs' };

/**
 * The specifier that imports `file` from a declaration file in `dir`.
 * @param {string} file absolute
 * @param {string} dir absolute
 */
export function specifier(file, dir) {
    const between = relative(dir, file);
    // On another Windows drive there is no relative path: import the file by its absolute one.
    let path = (isAbsolute(between) ? file : between).split(sep).join('/');
    for (const [source, emitted] of Object.entries(EMITTED)) if (path.endsWith(source)) path = path.slice(0, -source.length) + emitted;
    return path.startsWith('.') || isAbsolute(between) ? path : `./${path}`;
}

/**
 * The declaration file's text.
 * @param {import('./actions.js').ActionModule[]} modules
 * @param {object} options
 * @param {string} options.dir     where the file will be written, absolute
 * @param {string} options.source  where the actions came from, for the header
 */
export function declarations(modules, { dir, source }) {
    const lines = [];
    for (const module of modules) {
        const from = JSON.stringify(specifier(module.file, dir));
        const bare = handlerOf('', module.exports);
        if (bare) lines.push(`    ${JSON.stringify(module.name)}: typeof import(${from})[${JSON.stringify(bare)}];`);
        for (const exported of module.exports) {
            if (exported !== 'default') lines.push(`    ${JSON.stringify(`${module.name}#${exported}`)}: typeof import(${from})[${JSON.stringify(exported)}];`);
        }
    }
    return `// Generated by cyclewire from ${source}. Do not edit: it is written again when the actions change.

interface CycleWireActions {
${lines.join('\n')}
}

declare module 'virtual:cyclewire/actions' {
    const actions: import('cyclewire').ActionMap;
    export default actions;
}
`;
}

/**
 * Writes the file only when its text changes, so watchers do not loop.
 * @param {string} path absolute
 * @param {string} text
 * @returns {Promise<boolean>} whether it was written
 */
export async function writeIfChanged(path, text) {
    const current = await readFile(path, 'utf8').catch(() => null);
    if (current === text) return false;
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, text);
    return true;
}

/**
 * Writes the declarations for these modules to `path`.
 * @param {import('./actions.js').ActionModule[]} modules
 * @param {string} path absolute
 * @param {string} source
 */
export function writeDeclarations(modules, path, source) {
    return writeIfChanged(path, declarations(modules, { dir: dirname(path), source }));
}
